name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lerna bootstrap
        run: lerna bootstrap --hoist --force-local
      - name: Cache dependencies
        uses: actions/cache@v2
        env:
          cache-name: dependencies
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json')}}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}

  test-add:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Cache dependencies
        uses: actions/cache@v2
        env:
          cache-name: dependencies
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json')}}
      - name: Test add
        run: lerna run test --scope add --stream

  test-subtract:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Cache dependencies
        uses: actions/cache@v2
        env:
          cache-name: dependencies
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json')}}
      - name: Test subtract
        run: lerna run test --scope subtract --stream
